name: Generate Contribution Snake
on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  push:
    branches:
      - main
jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate snake SVG
        uses: platane/snk@v3
        with:
          output-image: dist/github-contribution-grid-snake.svg
      - name: Commit and push SVG
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "chore: update contribution snake"
          git push

