name: Generate Contribution Snake

# Elle de tetikleyebiliriz
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

# İzinleri tanımlıyoruz ki GITHUB_TOKEN ile commit edebilelim
permissions:
  contents: write

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: platane/snk@v3
        with:
          output-image: dist/github-contribution-grid-snake.svg

      - name: Commit and push SVG
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "chore: update contribution snake" || echo "No changes to commit"
          git push
